version: "3.8"

services:
  nest_park:
    container_name: nest-park
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest_park
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
