/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client";
import * as $Enums from "./enums.js";
import type * as Prisma from "./internal/prismaNamespace.js";

export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  mode?: Prisma.QueryMode;
  not?: Prisma.NestedStringFilter<$PrismaModel> | string;
};

export type EnumTipoVagaFilter<$PrismaModel = never> = {
  equals?: $Enums.TipoVaga | Prisma.EnumTipoVagaFieldRefInput<$PrismaModel>;
  in?: $Enums.TipoVaga[] | Prisma.ListEnumTipoVagaFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.TipoVaga[]
    | Prisma.ListEnumTipoVagaFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumTipoVagaFilter<$PrismaModel> | $Enums.TipoVaga;
};

export type BoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean;
};

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  mode?: Prisma.QueryMode;
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedStringFilter<$PrismaModel>;
  _max?: Prisma.NestedStringFilter<$PrismaModel>;
};

export type EnumTipoVagaWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TipoVaga | Prisma.EnumTipoVagaFieldRefInput<$PrismaModel>;
  in?: $Enums.TipoVaga[] | Prisma.ListEnumTipoVagaFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.TipoVaga[]
    | Prisma.ListEnumTipoVagaFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumTipoVagaWithAggregatesFilter<$PrismaModel>
    | $Enums.TipoVaga;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumTipoVagaFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumTipoVagaFilter<$PrismaModel>;
};

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedBoolFilter<$PrismaModel>;
  _max?: Prisma.NestedBoolFilter<$PrismaModel>;
};

export type EnumStatusTicketFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.StatusTicket
    | Prisma.EnumStatusTicketFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.StatusTicket[]
    | Prisma.ListEnumStatusTicketFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.StatusTicket[]
    | Prisma.ListEnumStatusTicketFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumStatusTicketFilter<$PrismaModel> | $Enums.StatusTicket;
};

export type EnumTipoTarifaFilter<$PrismaModel = never> = {
  equals?: $Enums.TipoTarifa | Prisma.EnumTipoTarifaFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.TipoTarifa[]
    | Prisma.ListEnumTipoTarifaFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.TipoTarifa[]
    | Prisma.ListEnumTipoTarifaFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumTipoTarifaFilter<$PrismaModel> | $Enums.TipoTarifa;
};

export type IntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedIntFilter<$PrismaModel> | number;
};

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string;
};

export type DateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null;
  in?:
    | Date[]
    | string[]
    | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
    | null;
  notIn?:
    | Date[]
    | string[]
    | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
    | null;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedDateTimeNullableFilter<$PrismaModel>
    | Date
    | string
    | null;
};

export type SortOrderInput = {
  sort: Prisma.SortOrder;
  nulls?: Prisma.NullsOrder;
};

export type EnumStatusTicketWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.StatusTicket
    | Prisma.EnumStatusTicketFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.StatusTicket[]
    | Prisma.ListEnumStatusTicketFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.StatusTicket[]
    | Prisma.ListEnumStatusTicketFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumStatusTicketWithAggregatesFilter<$PrismaModel>
    | $Enums.StatusTicket;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumStatusTicketFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumStatusTicketFilter<$PrismaModel>;
};

export type EnumTipoTarifaWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TipoTarifa | Prisma.EnumTipoTarifaFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.TipoTarifa[]
    | Prisma.ListEnumTipoTarifaFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.TipoTarifa[]
    | Prisma.ListEnumTipoTarifaFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumTipoTarifaWithAggregatesFilter<$PrismaModel>
    | $Enums.TipoTarifa;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumTipoTarifaFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumTipoTarifaFilter<$PrismaModel>;
};

export type IntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>;
  _sum?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedIntFilter<$PrismaModel>;
  _max?: Prisma.NestedIntFilter<$PrismaModel>;
};

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>;
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>;
};

export type DateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null;
  in?:
    | Date[]
    | string[]
    | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
    | null;
  notIn?:
    | Date[]
    | string[]
    | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
    | null;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel>
    | Date
    | string
    | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>;
};

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedStringFilter<$PrismaModel> | string;
};

export type NestedEnumTipoVagaFilter<$PrismaModel = never> = {
  equals?: $Enums.TipoVaga | Prisma.EnumTipoVagaFieldRefInput<$PrismaModel>;
  in?: $Enums.TipoVaga[] | Prisma.ListEnumTipoVagaFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.TipoVaga[]
    | Prisma.ListEnumTipoVagaFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumTipoVagaFilter<$PrismaModel> | $Enums.TipoVaga;
};

export type NestedBoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean;
};

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedStringFilter<$PrismaModel>;
  _max?: Prisma.NestedStringFilter<$PrismaModel>;
};

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedIntFilter<$PrismaModel> | number;
};

export type NestedEnumTipoVagaWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TipoVaga | Prisma.EnumTipoVagaFieldRefInput<$PrismaModel>;
  in?: $Enums.TipoVaga[] | Prisma.ListEnumTipoVagaFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.TipoVaga[]
    | Prisma.ListEnumTipoVagaFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumTipoVagaWithAggregatesFilter<$PrismaModel>
    | $Enums.TipoVaga;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumTipoVagaFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumTipoVagaFilter<$PrismaModel>;
};

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedBoolFilter<$PrismaModel>;
  _max?: Prisma.NestedBoolFilter<$PrismaModel>;
};

export type NestedEnumStatusTicketFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.StatusTicket
    | Prisma.EnumStatusTicketFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.StatusTicket[]
    | Prisma.ListEnumStatusTicketFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.StatusTicket[]
    | Prisma.ListEnumStatusTicketFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumStatusTicketFilter<$PrismaModel> | $Enums.StatusTicket;
};

export type NestedEnumTipoTarifaFilter<$PrismaModel = never> = {
  equals?: $Enums.TipoTarifa | Prisma.EnumTipoTarifaFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.TipoTarifa[]
    | Prisma.ListEnumTipoTarifaFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.TipoTarifa[]
    | Prisma.ListEnumTipoTarifaFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumTipoTarifaFilter<$PrismaModel> | $Enums.TipoTarifa;
};

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string;
};

export type NestedDateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null;
  in?:
    | Date[]
    | string[]
    | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
    | null;
  notIn?:
    | Date[]
    | string[]
    | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
    | null;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedDateTimeNullableFilter<$PrismaModel>
    | Date
    | string
    | null;
};

export type NestedEnumStatusTicketWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.StatusTicket
    | Prisma.EnumStatusTicketFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.StatusTicket[]
    | Prisma.ListEnumStatusTicketFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.StatusTicket[]
    | Prisma.ListEnumStatusTicketFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumStatusTicketWithAggregatesFilter<$PrismaModel>
    | $Enums.StatusTicket;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumStatusTicketFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumStatusTicketFilter<$PrismaModel>;
};

export type NestedEnumTipoTarifaWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TipoTarifa | Prisma.EnumTipoTarifaFieldRefInput<$PrismaModel>;
  in?:
    | $Enums.TipoTarifa[]
    | Prisma.ListEnumTipoTarifaFieldRefInput<$PrismaModel>;
  notIn?:
    | $Enums.TipoTarifa[]
    | Prisma.ListEnumTipoTarifaFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedEnumTipoTarifaWithAggregatesFilter<$PrismaModel>
    | $Enums.TipoTarifa;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumTipoTarifaFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumTipoTarifaFilter<$PrismaModel>;
};

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>;
  _sum?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedIntFilter<$PrismaModel>;
  _max?: Prisma.NestedIntFilter<$PrismaModel>;
};

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>;
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>;
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number;
};

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>;
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>;
};

export type NestedDateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null;
  in?:
    | Date[]
    | string[]
    | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
    | null;
  notIn?:
    | Date[]
    | string[]
    | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
    | null;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?:
    | Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel>
    | Date
    | string
    | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>;
};

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null;
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null;
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null;
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null;
};
