/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const TipoVaga = {
  PADRAO: "PADRAO",
  CADEIRANTE: "CADEIRANTE",
  IDOSO: "IDOSO",
  MANUTENCAO: "MANUTENCAO",
} as const;

export type TipoVaga = (typeof TipoVaga)[keyof typeof TipoVaga];
