/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const TipoVaga = {
  PADRAO: "PADRAO",
  CADEIRANTE: "CADEIRANTE",
  IDOSO: "IDOSO",
  MANUTENCAO: "MANUTENCAO",
} as const;

export type TipoVaga = (typeof TipoVaga)[keyof typeof TipoVaga];

export const StatusTicket = {
  PENDENTE: "PENDENTE",
  PAGO: "PAGO",
  CANCELADO: "CANCELADO",
} as const;

export type StatusTicket = (typeof StatusTicket)[keyof typeof StatusTicket];

export const TipoTarifa = {
  DIARIA: "DIARIA",
  MENSAL: "MENSAL",
  PRIMEIRA_HORA_MAIS_HORA_ADICIONAL: "PRIMEIRA_HORA_MAIS_HORA_ADICIONAL",
} as const;

export type TipoTarifa = (typeof TipoTarifa)[keyof typeof TipoTarifa];
